{
  "hash": "9203c0a87d810d0230487536fa2c671c",
  "result": {
    "markdown": "---\ntitle: \"Manipulating an API to find every single IMAX in the world\"\ndescription: \"IMAX Theaters have seen a resurrgence with the advent of cinematic blockbusters like Dune and Oppenheimer. However, getting information about these IMAXes is notoriously difficult. I scrape the underlying Algolia-based search engine on imax.com to find every single IMAX location in the world.\"\nauthor: \"Abhi Agarwal\"\ndate: \"2024-03-08\"\ncategories: [python, movies]\ndraft: true\nfreeze: true\n---\n\nAfter not really caring about movies, I suddenly developed an obsession with watching movies. Not necessarily the watching of movies themselves, but the *act* of watching movies. My number #1 icebreaker is trying to sell someone on the AMC Stubs A-List, with the same \"hey! if you watch like two movies a month, you'll break even :)\"^[this has not worked]. To me, going to the cinema and sitting down is a sacred experience. This has only become more prevalent as I've graduated college, with my number one concern most days is \"how do I kill time?\"\n\nAfter COVID-19 and the rise of streaming services, the global box office has seen an overall plunge. However, with the advent of Christopher Nolan's Oppenheimer, Premium Large Formats (PLFs) have became all the rage, especially with the coveted IMAX 70mm, of which there are only 7 in the United States. In order for cinema to survive, it must become associated with luxury and prestige, and IMAX leads the forefront of this.\n\n![Photo by <a href=\"https://unsplash.com/@ballistic?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash\">Isaac Moore</a> on <a href=\"https://unsplash.com/photos/amc-imax-building-wjLBQz2nvzE?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash\">Unsplash</a>](imax_backdrop.jpeg){.preview-image}\n\nBehind every great industry is a lie, and in this case, it's literally called LieMAX. IMAX, fervently hoping to expand, decided to slighty change what an \"IMAX\" is. Hoping to retrofit their theaters onto existing ones without new architecture. To the average person this isn't a big deal, but for weirdos like me with hypertuned preferences. And you should care, because you're getting a suboptimal experience for the exact same price as everyone else!\n\n# Finding where IMAX stores its secrets\n\nThere is no centralized list of IMAX theaters in the world. There's a few resources that have been hand-maintained by a few brave cinephiles, but most are out of date and incomplete. But I would guess that the IMAX company themselves stores this, right?\n\nOn [imax.com](https://imax.com), let's investigate the \"Find a Theatre\" option hiding in the footer of the page. This takes us to a theater find where if you enter a string of nearly *anything*, it gives you a list of theaters that match. Since the page isn't refreshing on every request, we can assume that there is some underlying API that's being requsted by the browser and being transformed into HTML markup with some client-side Javascript. Let's pop open Chrome DevTools and use my favorite invention in the entire world, the \"Network Tab\".\n\n![](screenshots/devtools.png)\n\nOk. That's not very helpful. We see a bunch of Javascript files, a bunch of fonts (woff2), CSS, a bunch of junk. Did y'all really need to send me 4.3MB of precious data to see some theaters?\n\nIf we filter by \"Fetch/XHR\" requests, we find exactly what we're looking for.\n\n![](screenshots/fetch_xhr.png)\n\nStill a bunch of junk, but a needle in our haystack. Notice there seems to be something calling a \"query\" endpoint. Let's click on it.\n\n![](screenshots/algolia_preview.png)\n\nHoly shit! That's our sauce. \n\nIf we right click that specific XHR request and click Copy > Copy as cURL, we get a string that allows us to perfectly emulate the request, including the specific headers and cookie information. Now, let me introduce my second favorite invention, [curlconverter.com](https://curlconverter.com). By taking this string and copy-pasting, we can get a snippet of code that perfectly replicates this in your favorite programming language.\n\n::: {#931cc37f .cell execution_count=1}\n``` {.python .cell-code}\nimport requests\n\nheaders = {\n    \"Accept\": \"*/*\",\n    \"Accept-Language\": \"en-US,en;q=0.9\",\n    \"Connection\": \"keep-alive\",\n    \"Origin\": \"https://www.imax.com\",\n    \"Sec-Fetch-Dest\": \"empty\",\n    \"Sec-Fetch-Mode\": \"cors\",\n    \"Sec-Fetch-Site\": \"cross-site\",\n    \"User-Agent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36\",\n    \"content-type\": \"application/x-www-form-urlencoded\",\n    \"sec-ch-ua\": '\"Chromium\";v=\"122\", \"Not(A:Brand\";v=\"24\", \"Google Chrome\";v=\"122\"',\n    \"sec-ch-ua-mobile\": \"?0\",\n    \"sec-ch-ua-platform\": '\"macOS\"',\n    \"x-algolia-api-key\": \"7c9c8e2eadbdc26fb3b97b5db64a28dd\",\n    \"x-algolia-application-id\": \"10MXKGB0UH\",\n}\n\ndata = '{\"query\":\"\",\"aroundLatLng\":\"42.65717,-71.140878\",\"aroundRadius\":500000,\"attributesToRetrieve\":[\"*\"],\"hitsPerPage\":30}'\n\nresponse = requests.post(\n    \"https://10mxkgb0uh-dsn.algolia.net/1/indexes/dev_web23_showtimes/query?x-algolia-agent=Algolia%20for%20JavaScript%20(4.17.2)%3B%20Browser\",\n    headers=headers,\n    data=data,\n)\n```\n:::\n\n\nWe've now discovered that they're using something called \"Algolia\". A first search leads to their webpage called \"AI Search that understands\". [Sure, Jan](https://www.cnet.com/tech/computing/google-said-ai-over-140-times-in-its-two-hour-google-io-keynote/). Algolia seems to be a YC-funded SAAS that handles searching for companies a bit too lazy to manage an elastisearch instance themselves. That being said, it seems people really like them and their product offering is strong, so they're likely perfectly fine for a non-tech company like IMAX.\n\nA quick search for \"Algolia API\" brings me to some [wonderful documentation](https://www.algolia.com/doc/rest-api/search/). However, their search syntax is a bit esteroic and I'm a busy man. Instead of reverse-engineering everything and writing a bunch of `requests` crap, they publish a few API clients including one for [python](https://github.com/algolia/algoliasearch-client-python), my language of choice when I want to get down and dirty. From that, let's instantiate a client that pretends to be the imax.com website.\n\n::: {#4e0ebb2c .cell execution_count=2}\n``` {.python .cell-code}\nfrom algoliasearch.search_client import SearchClient\n\nclient = SearchClient.create(\"10MXKGB0UH\", \"7c9c8e2eadbdc26fb3b97b5db64a28dd\")\n```\n:::\n\n\nNo errors! We're in.\n\nFrom the original request, we see that they're tapping into an \"index\" called `dev_web23_showtimes`. Following Algolia's documentation, it should be as easy as\n\n::: {#d551cb0b .cell execution_count=3}\n``` {.python .cell-code}\nshowtimes_index = client.init_index(\"dev_web23_showtimes\")\n```\n:::\n\n\nLet's see if we can get all of the movie theaters in the world. Following their documentation,\n\n::: {#21d795f8 .cell execution_count=4}\n``` {.python .cell-code}\nimport polars as pl\n\nresult = showtimes_index.search(\n    \"\",\n    request_options={\n        \"hitsPerPage\": 1000,\n        \"attributesToRetrieve\": [\n            \"*\",\n            \"-events\",\n            \"-movieSlugs\",\n            \"-movieVariantIds\",\n        ],\n        \"attributesToHighlight\": [],\n    },\n)\ntheaters_df = pl.from_dicts(result[\"hits\"])\ntheaters_df.glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 1000\nColumns: 15\n$ name              <str> '«Kinocentr» na Krasnoy Ploschadi IMAX', 'Zunyi Sky Square Jinyi & IMAX', 'Ziyang Wanda & IMAX', 'Zigong Wanda Plaza & IMAX', 'Zigong Seewell & IMAX Nanhu', 'Zibo Wanda & IMAX', 'Zibo Inzone Qina & IMAX', 'Zhuzhou LIVING MALL Hengdian & IMAX', 'Zhuji Wanda & IMAX', 'Zhuhai UNI PARK CGV & IMAX'\n$ slug              <str> '«kinocentr»-na-krasnoy-ploschadi-imax', 'zunyi-sky-square-jinyi-imax', 'ziyang-wanda-imax', 'zigong-wanda-plaza-imax', 'zigong-seewell-imax-nanhu', 'zibo-wanda-imax', 'zibo-inzone-qina-imax', 'zhuzhou-living-mall-hengdian-and-imax', 'zhuji-wanda-imax', 'zhuhai-uni-park-cgv-imax'\n$ address           <str> 'Astrahanskaja 99 - \"Krasnaja Ploshhad\"', '3F-A, Sky Square, No.9  Changzheng Avenue, Xinpu New District, Honghuagang District', '4F, No. 120 Jiaozi Avenue, Yanjiang District', '4F, Wanda Plaza, 1699 Huichuan Road, Ziliujing District', '3F Building No.5 - Huashang Shopping Mall - Huinan Road - HuiDong New District', '4F, Wanda Plaza, No. 17 Zhongrun Avenue, Zhangdian District', '7F, Zibo Inzone, No. 128, Liuquan Rd, Zhangdian District ', 'Floor 3, Area B, Phase I, LIVING Mall, No. 628 Xinhua West Road', '4F, Wanda Plaza, No.69 Huandong Street', '3rd Fl, Building 3, Zhuhai UNI PARK, Qianhe North Rd No. 96, Xiangzhou District'\n$ zip               <str> '353451', '563000', '641300', '643000', '643000', '255000', '255020', '412008', '311800', '519070'\n$ city              <str> 'Anapa', 'Zunyi', 'Ziyang', 'Zigong City, Sichuan', 'Zigong', 'Zibo, Shandong', 'Zibo', 'Zhuzhou City', 'Zhuji', 'Zhuhai, Guangdong Province'\n$ state             <str> '', '', '', '', '', '', '', 'Hunan Province', '', ''\n$ country           <str> 'RU', 'CN', 'CN', 'CN', 'CN', 'CN', 'CN', 'CN', 'CN', 'CN'\n$ countryName       <str> 'Russian Federation', 'China', 'China', 'China', 'China', 'China', 'China', 'China', 'China', 'China'\n$ region            <str> 'EUROPE', 'ASIA', 'ASIA', 'ASIA', 'ASIA', 'ASIA', 'ASIA', 'ASIA', 'ASIA', 'ASIA'\n$ timezone          <str> 'Europe/Moscow', 'Asia/Shanghai', 'Asia/Shanghai', 'Asia/Shanghai', 'Asia/Shanghai', 'Asia/Shanghai', 'Asia/Shanghai', 'Asia/Shanghai', 'Asia/Shanghai', 'Asia/Shanghai'\n$ _geoloc     <struct[2]> {'lat': 44.87959, 'lng': 37.3376}, {'lat': 27.7221742, 'lng': 107.069415}, {'lat': 30.13333, 'lng': 104.62725}, {'lat': 29.3279, 'lng': 104.7558}, {'lat': 29.32417, 'lng': 104.77912}, {'lat': 36.8394, 'lng': 117.9652}, {'lat': 36.81154, 'lng': 118.05682}, {'lat': 27.8434, 'lng': 113.162}, {'lat': 29.72344, 'lng': 120.28623}, {'lat': 22.2348, 'lng': 113.5246}\n$ amenities   <list[str]> ['stadiumSeating'], ['stadiumSeating'], None, ['stadiumSeating'], ['stadiumSeating'], ['stadiumSeating'], ['stadiumSeating'], None, ['stadiumSeating'], ['laser', 'stadiumSeating']\n$ objectType        <str> 'theatre', 'theatre', 'theatre', 'theatre', 'theatre', 'theatre', 'theatre', 'theatre', 'theatre', 'theatre'\n$ path              <str> 'theatre/«kinocentr»-na-krasnoy-ploschadi-imax', 'theatre/zunyi-sky-square-jinyi-imax', 'theatre/ziyang-wanda-imax', 'theatre/zigong-wanda-plaza-imax', 'theatre/zigong-seewell-imax-nanhu', 'theatre/zibo-wanda-imax', 'theatre/zibo-inzone-qina-imax', 'theatre/zhuzhou-living-mall-hengdian-and-imax', 'theatre/zhuji-wanda-imax', 'theatre/zhuhai-uni-park-cgv-imax'\n$ objectID          <str> 'theatre/«kinocentr»-na-krasnoy-ploschadi-imax', 'theatre/zunyi-sky-square-jinyi-imax', 'theatre/ziyang-wanda-imax', 'theatre/zigong-wanda-plaza-imax', 'theatre/zigong-seewell-imax-nanhu', 'theatre/zibo-wanda-imax', 'theatre/zibo-inzone-qina-imax', 'theatre/zhuzhou-living-mall-hengdian-and-imax', 'theatre/zhuji-wanda-imax', 'theatre/zhuhai-uni-park-cgv-imax'\n\n```\n:::\n:::\n\n\nWe're done! That's every single IMAX Theater in the world, approximately, uh, 1000? \n\nThat doesn't pass the sniff test.\n\nThis is a limitation of Algolia. If we inspect our original JSON response, we see that it actually does tell us how many total theaters in the world there are.\n\n::: {#0aefe891 .cell execution_count=5}\n``` {.python .cell-code}\nresult.pop(\"hits\")\ndisplay(result)\n```\n\n::: {.cell-output .cell-output-display}\n```\n{'nbHits': 1748,\n 'page': 0,\n 'nbPages': 1,\n 'hitsPerPage': 1000,\n 'exhaustiveNbHits': True,\n 'exhaustiveTypo': True,\n 'exhaustive': {'nbHits': True, 'typo': True},\n 'query': '',\n 'params': 'hitsPerPage=1000&attributesToRetrieve=%5B%22*%22%2C%22-events%22%2C%22-movieSlugs%22%2C%22-movieVariantIds%22%5D&attributesToHighlight=%5B%5D',\n 'renderingContent': {},\n 'processingTimeMS': 10,\n 'processingTimingsMS': {'_request': {'roundTrip': 119},\n  'afterFetch': {'format': {'decompress': 1, 'total': 8}, 'total': 9},\n  'total': 11},\n 'serverTimeMS': 11}\n```\n:::\n:::\n\n\nWe see that the `nbHits` is 1748. Algolia's search API only allows us to access [1000 results](https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/pagination/js/) in total, unless changed through an admin console. I looked, and the key I pulled is not an admin account, and it were I'd probably have the feds breaking down my door. In order to filter by any sort of string column, it has to be declared a \"facet\", and none of these columns have been declared that way. So I'm stuck with these 1000 results unless I figure out a good way to discriminate into the different\n\n## Breaking the world in half\n\nLet's go back to the drawing board. How did the original Algolia API work for figuring out which movie theater I want to go to? The original query string used on the website is `'{\"query\":\"\",\"aroundLatLng\":\"42.65717,-71.140878\",\"aroundRadius\":500000,\"attributesToRetrieve\":[\"*\"],\"hitsPerPage\":30}`. Searching google for `aroudnLatLng` leads to [documentation](https://www.algolia.com/doc/api-reference/api-parameters/aroundLatLng/) that links to Algolia's [guide on geolocation](https://www.algolia.com/doc/guides/managing-results/refine-results/geolocation/). Perhaps we could just pick a bunch of random points and radiuses and hope we cover the earth?\n\nSadly, this is probably not a great idea. The mathematical problem of fitting a bunch of circles such that it covers a surface is difficult, and I'm very much already a washed-up mathematician. I want to be respectful of IMAX's backend, given I looked at Algolia's pricing. \n\nThere is a solution, as Algolia also features the ability to search within a [rectangular box](https://www.algolia.com/doc/guides/managing-results/refine-results/geolocation/how-to/filter-results-inside-a-rectangle-area/). Given the entire world is standardized by the measures of latitude and longitude, all we have to do is split up the world into a bunch of squares and search within. \n\nI'm generally directionally challenged, so a special shoutout to ChatGPT who gave me the rectangulars used to divide the world into parts. \n\n::: {#9dd6db42 .cell execution_count=6}\n``` {.python .cell-code}\nquadrants = [\n    # Northwest Quadrant\n    (0, -180, 90, 0),\n    # Northeast Quadrant, split twice\n    # (0, 0, 90, 180),\n    # (0, 0, 45.0, 180),\n    (0, 0, 22.5, 180),\n    (22.5, 0, 45.0, 180),\n    (45.0, 0, 90, 180),\n    # Southwest Quadrant\n    (-90, -180, 0, 0),\n    # Southeast Quadrant\n    (-90, 0, 0, 180),\n]\n\nhits: list = []\nfor quadrant in quadrants:\n    quad_hits = showtimes_index.search(\n        \"\",\n        request_options={\n            \"hitsPerPage\": 1000,\n            \"attributesToRetrieve\": [\n                \"*\",\n                \"-events\",\n                \"-movieSlugs\",\n                \"-movieVariantIds\",\n            ],\n            \"attributesToHighlight\": [],\n            \"insideBoundingBox\": [list(float(val) for val in quadrant)],\n        },\n    )[\"hits\"]\n    print(len(quad_hits), quadrant)\n    hits.extend(quad_hits)\nprint(len(hits))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n530 (0, -180, 90, 0)\n93 (0, 0, 22.5, 180)\n912 (22.5, 0, 45.0, 180)\n155 (45.0, 0, 90, 180)\n27 (-90, -180, 0, 0)\n28 (-90, 0, 0, 180)\n1745\n```\n:::\n:::\n\n\nI needed to split the box corresponding to the Northeast into multiple rectangles to avoid hitting the 1000 limit. The world has been split up into 7 recentagles, each retrieving the entire list of IMAX theaters. We've found 1745 total theaters.\n\n3 theaters seem to be missing. What gives? Let's go back to the original 1000 sample of the IMAX theaters, filtering for any locations that doesn't have location data.\n\n::: {#35a51188 .cell execution_count=7}\n``` {.python .cell-code}\nmissing_geoloc_theaters = theaters_df.filter(pl.col(\"_geoloc\").is_null())\nmissing_geoloc_theaters.glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 3\nColumns: 15\n$ name              <str> 'Zhuhai Huafa Omnijoi & IMAX', 'Luzhou Tianyuan Jinyi & IMAX', 'Hohhot Huis Wanda & IMAX'\n$ slug              <str> 'zhuhai-huafa-omnijoi-imax', 'luzhou-tianyuan-jinyi-imax', 'hohhot-huis-wanda-imax'\n$ address           <str> '1303, Unit 2, Building 7, Poly Times, No.515 Shanhuhai Road, Hongqi Town, Jinwan District', '4F, Building 1, Tianyuan Plaza, Lanan Avenue, Jiangyang District ', '4F, Wanda Plaza, West Genghis Khan Street, Huis District'\n$ zip               <str> '519090', '646000', '010030'\n$ city              <str> 'Zhuhai City', 'Luzhou', 'Hohhot'\n$ state             <str> '', '', ''\n$ country           <str> 'CN', 'CN', 'CN'\n$ countryName       <str> 'China', 'China', 'China'\n$ region            <str> 'ASIA', 'ASIA', 'ASIA'\n$ timezone          <str> None, None, None\n$ _geoloc     <struct[2]> {'lat': None, 'lng': None}, {'lat': None, 'lng': None}, {'lat': None, 'lng': None}\n$ amenities   <list[str]> ['laser', 'stadiumSeating'], ['stadiumSeating'], ['stadiumSeating']\n$ objectType        <str> 'theatre', 'theatre', 'theatre'\n$ path              <str> 'theatre/zhuhai-huafa-omnijoi-imax', 'theatre/luzhou-tianyuan-jinyi-imax', 'theatre/hohhot-huis-wanda-imax'\n$ objectID          <str> 'theatre/zhuhai-huafa-omnijoi-imax', 'theatre/luzhou-tianyuan-jinyi-imax', 'theatre/hohhot-huis-wanda-imax'\n\n```\n:::\n:::\n\n\nFrom the `path` column and going to `imax.com/theatre/{path}`, I'm met with a `Application error: a client-side exception has occurred (see the browser console for more information).`, and the console tells me that it has to do with a null-reference error. I guess these theaters aren't ready for primetime yet ¯\\\\\\_(ツ)_/¯ \n\nSince I don't want to pollute my data, I'm gonna ignore them. Let's assemble our final dataframe, dropping some unneeded columns.\n\n::: {#5811c1a1 .cell execution_count=8}\n``` {.python .cell-code}\nfrom itables import show\nall_theaters_df = (\n    pl.from_dicts(hits)\n    .sort(pl.col(\"slug\"))\n    .drop([\"path\", \"objectID\", \"objectType\", \"fandangoTmsId\"])\n    .with_columns(\n        pl.when(pl.col(pl.Utf8).str.len_bytes() == 0)\n        .then(None)\n        .otherwise(pl.col(pl.Utf8))\n        .name.keep()\n    )\n)\nshow(all_theaters_df)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div class=\"itables\">\n<style>.itables table td {\n    text-overflow: ellipsis;\n    overflow: hidden;\n}\n\n.itables table th {\n    text-overflow: ellipsis;\n    overflow: hidden;\n}\n\n.itables thead input {\n    width: 100%;\n    padding: 3px;\n    box-sizing: border-box;\n}\n\n.itables tfoot input {\n    width: 100%;\n    padding: 3px;\n    box-sizing: border-box;\n}\n\n.itables { font-size: medium; }\n\n.itables select, .itables input {\n    color: inherit;\n}\n</style>\n<table id=\"itables_9fe84a6d_380d_48ea_bde3_d356b7b2cf46\" class=\"display nowrap\" data-quarto-disable-processing=\"true\" style=\"table-layout:auto;width:auto;margin:auto;caption-side:bottom\">\n<thead>\n    <tr style=\"text-align: right;\">\n      \n      <th>name</th>\n    </tr>\n  </thead><tbody><tr><td>Loading... (need <a href=https://mwouts.github.io/itables/troubleshooting.html>help</a>?)</td></tr></tbody>\n\n</table>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css\">\n<script type=\"module\">\n    // Import jquery and DataTable\n    import 'https://code.jquery.com/jquery-3.6.0.min.js';\n    import dt from 'https://cdn.datatables.net/1.12.1/js/jquery.dataTables.mjs';\n    dt($);\n\n    $(document).ready(function () {\n        document.querySelectorAll(\"#itables_9fe84a6d_380d_48ea_bde3_d356b7b2cf46:not(.dataTable)\").forEach(table => {\n            // Define the table data\n            const data = [[\"109 Cinemas Futako Tamagawa & IMAX\"]];\n\n            // Define the dt_args\n            let dt_args = {\"order\": [], \"fnInfoCallback\": function (oSettings, iStart, iEnd, iMax, iTotal, sPre) { return sPre + ' (<a href=\"https://mwouts.github.io/itables/downsampling.html\">downsampled</a> from 1,745x13 to 1x1 as maxBytes=65536)'; }, \"dom\": \"ti\"};\n            dt_args[\"data\"] = data;\n\n            \n            new $.fn.dataTable(table, dt_args);\n        });\n    });\n</script>\n</div>\n```\n:::\n:::\n\n\n# Map of every IMAX in the world\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3 (ipykernel)\n    language: python\n    name: python3\n---\n",
    "supporting": [
      "index_files/figure-ipynb"
    ],
    "filters": []
  }
}