project:
  type: website
  preview:
    port: 8012

website:
  title: Abhi Agarwal
  site-url: "https://abhiaagarwal.com"
  repo-url: "https://github.com/abhiagarwal01/abhiagarwal01"
  twitter-card: true
  open-graph:
    locale: en_US
  google-analytics:
    tracking-id: "G-LL44DGVQD9"
    storage: none
    anonymize-ip: true
  comments:
    giscus:
      repo: "abhiagarwal01/abhiagarwal01"
      repo-id: "R_kgDOIZa_6w"
      category: "Comments"
      category-id: "DIC_kwDOIZa_684CTpsj"
      mapping: "og:title"
      theme: "preferred_color_scheme"
      input-position: "top"
  navbar:
    right:
      - about.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/abhiagarwal01
        aria-label: Github
      - icon: twitter
        href: https://twitter.com/abhiaaaaagarwal
        aria-label: Twitter

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
