project:
  type: website
  preview:
    port: 8012
filters:
   - include-code-files
website:
  title: Abhi Agarwal
  site-url: "https://abhi.rodeo"
  repo-url: "https://github.com/abhiagarwal01/abhiagarwal01"
  twitter-card: true
  open-graph:
    locale: en_US
  google-analytics:
    tracking-id: "G-LL44DGVQD9"
    storage: none
    anonymize-ip: true
  comments:
    giscus:
      repo: "abhiagarwal01/abhiagarwal01"
      repo-id: "R_kgDOIZa_6w"
      category: "Comments"
      category-id: "DIC_kwDOIZa_684CTpsj"
      mapping: "og:title"
      theme: "preferred_color_scheme"
      input-position: "top"
  navbar:
    title: false
    pinned: true
    right:
      - about/index.qmd
      - blog/index.qmd
      - icon: github
        href: https://github.com/abhiagarwal01
        aria-label: Github

format:
  html:
    highlight-style: github
    html-math-method: mathml
    theme:
      light: [litera, "assets/styles/theme.scss"]
      dark: [litera, "assets/styles/theme.scss", "assets/styles/dark.scss"]
    header-includes: >
      <link rel="preconnect" href="https://rsms.me/">
      <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/firacode@6.2.0/distr/fira_code.css">
