[tool.poetry]
name = "abhiagarwal01"
version = "0.1.0"
description = "Python dependencies for my Blog"
authors = ["Abhi Agarwal <abhiaagarwal01@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jupyter = "^1.0.0"
jupyter-cache = "^1.0.0"
radian = "^0.6.5"
pydantic = "2.4.0"
devtools = "^0.12.2"
rich = "^13.7.1"
nbformat = "^5.9.2"
polars = "^0.20.4"
algoliasearch = "^3.0.0"
ipyleaflet = "^0.18.2"
itables = {extras = ["polars"], version = "^1.7.1"}
lxml = "^5.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
