---
title: "I got a job. How the fuck am I supposed to use my money?"
description: ""
author: "Abhi Agarwal"
date: "2023-04-30"
categories: [finance]
draft: true
---

# Introduction

I may have recently graduated from college with a degree in Economics, but I can confidently tell you that I had no idea how the fuck to handle my money. 

But don't worry, this is not a reflection on you. You likely were never taught how to manage money, through no fault of your own. My take is that the financial industry has a strong monetary motive to keep people misguided, in order to extract money by tricking people into debts and getting them to pay for expensive financial planners that offer the same boilerplate you can find on google. 

But it really doesn't have to be this way!

I spent a whole week reading through websites, reddit threads, and asking some close family friends and compiled a list of tips on how to effectively manage your money. There is no golden goose, none of these will turn you into a millionaire overnight. However, by investing passively, keeping an eye on the margins, and keeping your finances actively managed, you can someday, turn yourself into a millionaire. 

While this guide is targeted towards people with their first job straight out of college with a degree, this is also applicable to those above 18 years old. If you're a college student working part-time, or a high-schooler who wants to start building credit, this guide can still be helpful. Hey, even if you're a seasoned veteran with the system, hopefully this teach you a trick or two.

I would first like to caution that I am not a financial advisor, I am just a guy who spent a lot of time googling and researching. I'll cite any major claims I make. I am not liable for any advice of mine you follow, nor am I liable for any advice you don't follow.  

In addition, I was fortunate enough to graduate college with no debts and immediately find a high-paying job. I'm writing this from a financially neutral prespective, but can't guarantee that I'll be able to fully remove the implicit biases that come with my 0.01% fortunate world experiences from my writing. I'll do my best. 

# The Yak-Shaving

## Get a budgeting app

## Open a High-Yield Savings acccount (HYSA)

Many banks offer high-yield (interest) savings accounts. This is partly a consequence of our macroeconomic times with high interest rates. Many banks that offer high interest rates are often online banks, as they don't have to manage the costs of managing an in-person bank and thus are able to offer high rates. 

And that debit card you got from that savings account? Lock it. Unless you're withdrawing money from an ATM, there should be no reason to ever use your debit card for purchasing. 

### SoFi

**NOTE: I currently am a customer of SoFi. I am not paid by them to give my opinion.**

SoFi is a relatively new bank that I discovered because of the Super Bowl. As an online-only bank, they're able to offer (as of 5/6/22) a 4.20% APY savings account. 

The catch is that you need to have over $1,000 of direct deposits per month with them in order to access this rate, which grants you free access to their membership called "SoFi Plus". They also offer a checking account with a 1.20% APY — however, you simply don't need to use your checking account at all, instead depositing a minimal amount and turning on their free "Overdraft Protection", which just draws money directly from your saving if you risk going into overdraft. If you use a credit card, you can have the autopay set up to pull directly from your savings account when the money is due, meaning you gain interest on that money before it's used to pay your credit card.

SoFi also has a points system where 1 point corresponds to 1 cent. By linking other financial accounts, such as your 401k, Roth IRA, or just other bank accounts accounts at different institutions, SoFi will give you points. You even get points for logging into the app for consecutive days. If you have SoFi plus, some of these point totals double  — for example, linking a financial account gives 25 points, but I get exactly 50 points, so half a dollar quite literally for free. These amounts may seem small, but if you consistently do them, it can add up quickly. 

Your points are also instantly convertible, unlike other options which require waiting until the end of the year. Thus, you can redeem those points as liquid directly into HYSA, which then begins accumulating interest. As of 5/6/22, I've redeemed over $200 dollars worth of points with about a $4k spend, so a return rate of about 5%^[Obviously, this will slow down as I've exhausted most of their "gimmes", but it's still pretty great nonetheless]. 

If you know how to game it, SoFi is an awesome starting bank. They aggressively seem to be targeting younger people in particular trying to be an all-in-one solution, offering banking services, credit cards, investment options, student loans, personal loans, etc. I personally only use the banking and credit card services, but be warned, they will advertise the other options to you aggressively. As much as I'm praising SoFi, at the end of the day, like any other financial company their goal is to figure out ways to extract money from the so-called "chumps" — don't be one.

## Open credit, and treat it like debit

Credit cards are freaking awesome. They're essentially a short-term loan every single month that comes with strong benefits, offering fraud protection and the ability to gain a bit of cash with every purchase, just to name a few standard perks. Credit cards will often reimburse you extra for dining, groceries, gas, or even give you a credit for common streaming services and delivery apps such as DoorDash and Uber Eats.

Unfortunately, credit cards *work* because of the loaning aspect. Credit card companies are able to offer strong benefits because of a calculated strategy that some percentage of their holders will be unable to pay back that loan, locking them into high interest debt.

The golden rule of credit cards is to *treat them exactly like debit cards*. Never spend more money than you have, and always pay exactly what you owe on your bill^[Though I recommend delaying the bill to the very last day it's due — your money gains interest in the meantime].

### No-Annual Fee Cards

#### Capital One SavorOne

The Capital One SavorOne is an awesome beginner card

#### SoFi Mastercard

If you have the SoFi Bank Account and have SoFi plus (read above), the SoFi Mastercard is a no-brainer. If you have SoFi Plus, you get 3% flat cashback on fewer than $2,000 purchases per month and 2% flat otherwise, which is a ridiculously good deal, especially if you you have low expenses. However, the 3% rate only lasts for 12 months after SoFi Plus has been activated, making it a good candidate as a first-time card. They approved me instantly after opening an account.

This card also doesn't have a foreign transcation fee. I did not know this when I got the card, but immediately after I lived in Switzerland for 3 months for work, and I probably saved hundreds of dollars. 

#### Bilt Mastercard

This one is a bit of an odd card. While it seems unimposing at first glance, the Bilt card has a superpower in that you can pay rent with it, gaining rewards on what is likely your largest purchase of the month. While this is accomplishable with other credit cards by using apps, the fees they charge often outweigh the rewards. Bilt mimmicks the common payment processors you use to pay rent with the credit card as a backend, essentially allowing you to pay rent on credit. 

It's not entirely a free lunch — in order to qualify for the rewards, you need to make 5 additional purchases. They offer strong cashback on categories such as eating out, so this isn't particularly hard to qualify for. 

I personally don't use this card, nor am I looking to get one since I'm currently living with my parents and not paying rent. The moment I sign my first lease, I will be getting the Bilt Mastercard. 

### Annual Fee Cards

Fee cards offer excellent perks, but require an annual fee. This fee is often worth it through benefits, but you need to be pragmatic and smart to make good use of it, as the company is making money off people *not* taking advantage. If you're just starting out or have low expenses, an annual fee card may not be for you. 

#### Chase Sapphire Preferred / Reserve

#### Capital One VentureX

#### American Express Gold

And not to be particularly vain, but the card itself looks *gorgeous*. I think that justifies just a little bit of the annual fee. 

# Using your money

## A primer on compound interest, the strongest drug in the world

## Emergency Fund

## Take advantage of the tax-advantaged accounts

### 401(k)

Your 401k is your best way to become a millionaire. Your 401k is a retirement account, designed 

I currently max out my 401(k) at about 20k a year. This reduces my tax burden by around $15,000. My employer currently matches 6% at 100%. Assuming a 7% rate of return on my 401k, by age 42, I would have $1,051,522 dollars, officially making me a millionaire. At age 59.5, the age you can start withdrawing your 401(k) without penalty, I would have $4 million. At age 72, the year the IRS forces you to withdraw all your money, I would have $10,000,000.

### Roth IRA

### Health Savings Account (HSA)

### 529

## Pay debts

If you just graduated college, you likely have some debts. And if you need to keep spending money to make money, you may continue to accumulate debts.

## You are not smarter than the market.

We all hear about the successes of people who beat the market, whether through careful analysis or hitting on the correct meme stocks and riding the wave. However, for every success, there are 999 different failures. 

The market operates on collective wisdom. To beat the market.

It's just not worth the hastle.

That being said, there is real merit to at least *trying*. My father was able to get 10-20% returns on a sum he invested in my education, which enabled me to graduate from college debt-free. But he was able to do so as he had financial flexibility. I'm enternally grateful that I'm in the universe where the 0.1% odds happened — I fear for the parallel universes where the 99.9% happened. 

I personally follow a philosophy of passive investing, where your money is put into index funds tied into the overall performance of the market. 

# The greatest investment: yourself

Ha, I got you didn't I, I bet you didn't expect this classic cliche! 

## Health

Anyways, your money is not a reflection of you, but rather a reflection of the way you live. Get a gym membership, and get a personal trainer if it helps you stick to your goals (I absolutely need mine) to focus on your physical health. America is one of the worst places in the world to be sick or with a chronic disease, and your bills will eventually reflect that. Spend a bit more money on groceries to get higher-quality products to cook healthier food for yourself, or a meal-planning service that will send meals for you.

Go get a therapist^[which you can fund with your HSA, btw!] and focus on keeping your mind healthy. Humans are just not built for 9-5, and the associated complexities with modern capitalism. I bet you're exhausted reading this far, and man, let me tell you that I'm exhausted writing this far. 

## Don't hustle

"Side hustling" is a thing that for some reason we glamorize. In a well-functioning society, should people *really* be working an additional 10-20 hours a week just to pick up a bit of extra cash? 

Just from an opportunity cost prespective, let's say you spend 40 hours a week on your job, and 20 hours on your side hustle. It's 100% likely that your performance in your main job will suffer, hurting your opportunities to develop skills in that job and deny you future income. I went through the same thing, in believing I was a superhuman that could cognitively and physically handle additional work. 

Again, this advice is situational. If you're working a job that's meant to be a temporary shortgap, side hustling can provide you the ability to develop other skills that can later be converted to a full hustle. If you definitely need the cash, then side hustling may be your only means to get that extra cash. 

## Live for the future, but the future could just end tomorrow

While all of this advice takes the. You could be struck by lightning tomorrow and die. You could live frugally for 40 years, then be diagnosed with Alzheimer's and never get to enjoy your saved retirement money. You have to survive today to see tomorrow. 

Everyone's balance is different. Some people like to spend lavishly now, while other people choose to live acesticly. 

# Conclusion